---
ci:
    autoupdate_schedule: quarterly

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
          - id: black
            language_version: python3 # Should be a command that runs python3.6+

    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
            args: [--count, --show-source, --statistics]

    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.5.0
      hooks:
          - id: setup-cfg-fmt

    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.28.1
      hooks:
          - id: check-github-workflows

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.2
      hooks:
          - id: pyupgrade
            args: [--py37-plus]
