---
name: Continuous Integration

on: [push, pull_request]

jobs:
    pre-commit:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - uses: pre-commit/action@v2.0.0
